FROM "luck/latex-base:latest"

#
# Try using
#
#  tlmgr search --global --file <missing thing>
#
# to figure out what you need to install.
#
# I know "scheme-full" is tempting.  But three hours later you may have wished you picked out the packages...
#
#
# RUN tlmgr install <things in sorted order...>

RUN tlmgr install \
    collection-basic \
    collection-fontsrecommended \
    collection-latex \
    tools \
    #end
    
