FROM "algorithms-fall2018-public/latex-base:latest"

RUN tlmgr install \
    asymptote \
    booktabs \
    ccicons \
    collection-fontsrecommended \
    fancyvrb \
    fpl \
    genmisc \
    hardwrap \
    l3kernel \
    l3packages \
    lipsum \
    listings \
    mathpazo \
    microtype \
    ms \
    relenc \
    setspace \
    siunitx \
    textcase \
    titlesec \
    tufte-latex \
    units \
    xcolor \
    xkeyval \

# blank line for sorting list above
